-- Lock the new table down like every other (no Data API access), then move the ventures that used to be
-- hard-coded in src/shared/ventures.ts into the database. Only My Fortune is live; the rest were prototype demos.
ALTER TABLE "ventures" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
INSERT INTO "ventures" ("slug", "name", "status", "sort", "data") VALUES
('my-fortune', 'My Fortune', 'live', 1, '{"tagline":"Experience the Luck","logoText":"MF","logoUrl":null,"coverUrl":null,"city":"Dundigal, Hyderabad","locality":"Gandimaisamma · near ORR","address":"Dundigal Gandimaisamma, Medchal-Malkajgiri, Telangana","pin":"500043","acres":"11","lat":17.5935,"lng":78.4405,"rera":"HMDA LP No. 000071/LO/Plg/HMDA/2021","amenities":["Play area","Open gym","Yoga park","Avenue plantation","Drinking water","LED street lighting","Amphitheatre"]}'),
('haritha-vanam', 'Haritha Vanam', 'draft', 2, '{"tagline":"Nature · Land · Living","logoText":"HV","logoUrl":null,"coverUrl":null,"city":"Hyderabad, Telangana","locality":"Near Outer Ring Road","address":"Survey No. 124, Haritha Vanam Road, Hyderabad, Telangana","pin":"500001","acres":"18.42","lat":17.462222,"lng":78.154444,"rera":"","amenities":["Grand entrance","Central park","Clubhouse"]}'),
('green-valley', 'Green Valley', 'draft', 3, '{"tagline":"Green · Valley · Living","logoText":"GV","logoUrl":null,"coverUrl":null,"city":"Hyderabad, Telangana","locality":"Near Outer Ring Road","address":"Survey No. 124, Green Valley Road, Hyderabad, Telangana","pin":"500001","acres":"18.42","lat":17.462222,"lng":78.154444,"rera":"","amenities":["Grand entrance","Central park","Clubhouse"]}'),
('lakeview-enclave', 'Lakeview Enclave', 'draft', 4, '{"tagline":"Lake · View · Living","logoText":"LE","logoUrl":null,"coverUrl":null,"city":"Shamshabad, Telangana","locality":"Near Airport Road","address":"Survey No. 87, Lakeview Road, Shamshabad, Telangana","pin":"501218","acres":"24.8","lat":17.2405,"lng":78.4298,"rera":"","amenities":["Grand entrance","Central park","Clubhouse"]}'),
('oak-county', 'Oak County', 'draft', 5, '{"tagline":"Open · Green · Living","logoText":"OC","logoUrl":null,"coverUrl":null,"city":"Yadadri, Telangana","locality":"Near Temple Road","address":"Survey No. 42, Oak County Road, Yadadri, Telangana","pin":"508115","acres":"31.2","lat":17.5927,"lng":78.9452,"rera":"","amenities":["Grand entrance","Central park","Clubhouse"]}')
ON CONFLICT ("slug") DO NOTHING;
